blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/nivisi/LeafyLauncher/wiki/Contribution-Guidelines#issues
    about: Please check out contribution guidelines before opening an issue.
