name: leafy_data
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  lints: ^1.0.0
dependencies:
  freezed_annotation: ^2.0.3
