name: 🪵 New Issues Branch Name Generator

# Just messing around GitHub Actions :)
# The purpose of this action is to drop a comment in the issue with the branch name generated based on the title and the labels.
# TODO: Support editing the issue (e.g. editing the comment).

on:
  issues:
    types:
      - opened

jobs:
  GenerateAndPostMessage:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Generate Branch Name
        id: generate_branch_name
        uses: actions/github-script@v5.0.0
        with:
          script: |
            // See https://github.com/SByteDev/BranchNameGenerator
            function generateBranchName(task, prefix, divider, version) {
               if (task === undefined || task === "") {
                  return "";
               }
               // Replace non-word characters with divider.
               var branch = task.replace(/([\W])/g, divider);
                 // Remove duplicated dividers.
               if (divider == "-") {
                  branch = branch.replace(/-+/g, divider);
               } else {
                  branch = branch.replace(/_+/g, divider);
               }
                 // Replace uppercase characters with lovercase characters.
               branch = branch.toLowerCase();
                 // Remove first divider.
               if (branch[0] === divider) {
                  branch = branch.substring(1, branch.length);
               }
               // Remove last divider.
               if (branch[branch.length - 1] === divider) {
                  branch = branch.substring(0, branch.length - 1);
               }
               if (prefix !== undefined && prefix !== "") {
                  // Add tack type folder.
                  branch = prefix + "/" + branch;
               }
               if (version !== undefined && version !== "") {
                  // Add version folder.
                  branch = version + "/" + branch;
               }
               return branch;
            };
            
            var branchPrefix;
            
            console.log("Getting labels")
            
            const labels = context.payload.issue.labels
            
            if (!labels) {
              branchPrefix = ""
            } else {
              for (index in labels) {
                const label = labels[index]
                if (label.name.includes("bug")) {
                  console.log("Found a bug label!");
                  if (branchPrefix == "feature") {
                    core.setFailed("The issue contains both bug and feature labels: that's not correct");
                  }
                  branchPrefix = "bug"
                }
                if (label.name.includes("feature")) {
                  console.log("Found a feature label!");
                  if (branchPrefix == "bug") {
                    core.setFailed("The issue contains both bug and feature labels: that's not correct");
                  }
                  branchPrefix = "feature"
                }
              }
            }
            
            console.log("Generating branch name ...");

            const branchName = generateBranchName(
              context.payload.issue.title,
              branchPrefix,
              "-",
              ""
            );
            
            core.setOutput("branch_name", branchName);

      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Autogenerated branch name:
            ```
            ${{ steps.generate_branch_name.outputs.branch_name }}
            ```
