name: Use Cases Validation

on:
   pull_request:
     types:
      - opened
      - edited
      - reopened
      - synchronize

   workflow_dispatch:

jobs:
  pr_usecases_validation:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Validate PR Use Cases
      uses: nivisi/dart_pull_request_use_case_validator@0.0.3
      with:
         github-token: ${{ github.token }}
